Repository the-collab-space/cinema-flix, pull requests merged in 2021-04, with the labels that each got.

#11 feat: first migration and entities configurations
  src/CinemaFlix.Application/Common/Interfaces/IApplicationDbContext.cs
  src/CinemaFlix.Application/Common/Interfaces/IMovieRepository.cs
  src/CinemaFlix.Infrastructure/CinemaFlix.Infrastructure.csproj
  src/CinemaFlix.Infrastructure/DependencyInjection.cs
  src/CinemaFlix.Infrastructure/Persistence/ApplicationDbContext.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/ActorConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/CharacterConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/DirectorConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/GenreConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/MovieConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/PictureConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Repositories/MovieRepository.cs
  src/CinemaFlix.Infrastructure/Persistence/Repositories/Repository.cs
  src/CinemaFlix.UI/CinemaFlix.UI.csproj
  src/CinemaFlix.UI/Pages/_ViewImports.cshtml
  src/CinemaFlix.UI/Startup.cs
  src/CinemaFlix.UI/appsettings.json
Labels: enhancement

#12 Feature/create entities
  src/CinemaFlix.Domain/Entities/Actor.cs
  src/CinemaFlix.Domain/Entities/Character.cs
  src/CinemaFlix.Domain/Entities/Director.cs
  src/CinemaFlix.Domain/Entities/Genre.cs
  src/CinemaFlix.Domain/Entities/Language.cs
  src/CinemaFlix.Domain/Entities/Movie.cs
  src/CinemaFlix.Domain/Entities/Picture.cs
  src/CinemaFlix.Domain/Entities/User.cs
  src/CinemaFlix.Domain/ValueObjects/Email.cs
  src/CinemaFlix.Domain/ValueObjects/Name.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/GenreConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/LanguageConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/MovieConfiguration.cs
Labels: refactor

#13 Feature/create migration
  src/CinemaFlix.Domain/Entities/User.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/ActorConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/CharacterConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/DirectorConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/UserConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Migrations/20210408024814_Initial.Designer.cs
  src/CinemaFlix.Infrastructure/Persistence/Migrations/20210408024814_Initial.cs
  src/CinemaFlix.Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
Labels: refactor

#14 fix: remove identity references and update packages
  src/CinemaFlix.UI/Areas/Identity/Pages/_ViewStart.cshtml
  src/CinemaFlix.UI/CinemaFlix.UI.csproj
  src/CinemaFlix.UI/Pages/Shared/_Layout.cshtml
  src/CinemaFlix.UI/Pages/Shared/_LoginPartial.cshtml
  src/CinemaFlix.UI/Startup.cs
Labels: bug

#16 Domain entities and database configuration
  src/CinemaFlix.Application/CinemaFlix.Application.csproj
  src/CinemaFlix.Application/Common/Interfaces/IMovieRepository.cs
  src/CinemaFlix.Application/Common/Interfaces/IRepository.cs
  src/CinemaFlix.Domain/Common/Entity.cs
  src/CinemaFlix.Domain/Entities/Actor.cs
  src/CinemaFlix.Domain/Entities/Character.cs
  src/CinemaFlix.Domain/Entities/Director.cs
  src/CinemaFlix.Domain/Entities/Genre.cs
  src/CinemaFlix.Domain/Entities/Language.cs
  src/CinemaFlix.Domain/Entities/Movie.cs
  src/CinemaFlix.Domain/Entities/Picture.cs
  src/CinemaFlix.Domain/Entities/User.cs
  src/CinemaFlix.Domain/ValueObjects/Email.cs
  src/CinemaFlix.Domain/ValueObjects/Name.cs
  src/CinemaFlix.Infrastructure/CinemaFlix.Infrastructure.csproj
  src/CinemaFlix.Infrastructure/DependencyInjection.cs
  src/CinemaFlix.Infrastructure/Persistence/ApplicationDbContext.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/ActorConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/BaseEntityConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/CharacterConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/DirectorConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/GenreConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/LanguageConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/MovieConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/PictureConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Configurations/UserConfiguration.cs
  src/CinemaFlix.Infrastructure/Persistence/Migrations/20210408024814_Initial.Designer.cs
  src/CinemaFlix.Infrastructure/Persistence/Migrations/20210408024814_Initial.cs
  src/CinemaFlix.Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
  src/CinemaFlix.Infrastructure/Persistence/Repositories/MovieRepository.cs
  src/CinemaFlix.Infrastructure/Persistence/Repositories/Repository.cs
  src/CinemaFlix.UI/Areas/Identity/Pages/_ViewStart.cshtml
  src/CinemaFlix.UI/CinemaFlix.UI.csproj
  src/CinemaFlix.UI/Data/ApplicationDbContext.cs
  src/CinemaFlix.UI/Data/Migrations/00000000000000_CreateIdentitySchema.Designer.cs
  src/CinemaFlix.UI/Data/Migrations/00000000000000_CreateIdentitySchema.cs
  src/CinemaFlix.UI/Data/Migrations/ApplicationDbContextModelSnapshot.cs
  src/CinemaFlix.UI/Pages/Shared/_Layout.cshtml
  src/CinemaFlix.UI/Pages/Shared/_LoginPartial.cshtml
  src/CinemaFlix.UI/Pages/_ViewImports.cshtml
  src/CinemaFlix.UI/Startup.cs
  src/CinemaFlix.UI/appsettings.json
Labels: enhancement
